name: Deploy Portafolio to GitHub Pages

on:
  push:
    branches: 
      - main  

permissions:
  contents: read
  pages: write 
  id-token: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código del portafolio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias del portafolio
        run: npm install

      - name: Construir el portafolio con Vite
        run: npm run build

      - name: Subir archivos generados del portafolio
        uses: actions/upload-pages-artifact@v2  
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Desplegar el portafolio en GitHub Pages
        uses: actions/deploy-pages@v2  